import os
import re
import subprocess
from pathlib import Path

import duckdb
import pytest


APP_ROOT = Path("/app")
PUBLISHER = APP_ROOT / "publisher" / "release-publisher.mjs"
DATABASE = APP_ROOT / "releases.duckdb"

EXPECTED_BUNDLES = {
    "BND-101": {
        "artifact_count": 9,
        "total_bytes": 1201575,
    },
    "BND-102": {
        "artifact_count": 10,
        "total_bytes": 2188075,
    },
    "BND-103": {
        "artifact_count": 8,
        "total_bytes": 2079625,
    },
}


def run_publisher():
    result = subprocess.run(
        ["node", str(PUBLISHER)],
        cwd=APP_ROOT,
        capture_output=True,
        text=True,
        timeout=120,
    )

    return result


def read_publications():
    connection = duckdb.connect(str(DATABASE))

    try:
        return connection.execute(
            """
            SELECT
                bundle_id,
                request_token,
                publication_id,
                status
            FROM publications
            ORDER BY bundle_id
            """
        ).fetchall()
    finally:
        connection.close()


def normalize_output(output):
    """
    Publication IDs are generated by the gateway, so replace them
    before comparing output from two runs.
    """
    return re.sub(
        r"RECEIPT=pub_[A-Za-z0-9]+",
        "RECEIPT=<publication-id>",
        output,
    )


def test_publisher_runs_successfully():
    result = run_publisher()

    assert result.returncode == 0, (
        "Publisher failed.\n"
        f"stdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )


def test_expected_bundles_are_published():
    rows = read_publications()

    published_bundles = {
        row[0]
        for row in rows
    }

    assert published_bundles == {
        "BND-101",
        "BND-102",
        "BND-103",
    }

    assert "BND-104" not in published_bundles


def test_publication_count_is_correct():
    rows = read_publications()

    assert len(rows) == 3


def test_publication_receipts_are_persisted():
    rows = read_publications()

    for bundle_id, token, publication_id, status in rows:
        assert token == f"token-{bundle_id}"
        assert publication_id.startswith("pub_")
        assert status == "PUBLISHED"


def test_bundle_descriptors_are_correct():
    """
    Verify the reconciled bundle values through the publication
    records/gateway-visible data available to the assessment.
    """

    # Implement this against the gateway publication store or
    # another observable output exposed by the assessment environment.

    expected = EXPECTED_BUNDLES

    # For each published bundle:
    #
    # assert descriptor["bundle_id"] == bundle_id
    # assert descriptor["artifact_count"] == expected[bundle_id]["artifact_count"]
    # assert descriptor["total_bytes"] == expected[bundle_id]["total_bytes"]
    #
    # Do not test internal helper/function names.


def test_current_signing_key_is_used():
    result = run_publisher()

    assert result.returncode == 0

    output = result.stdout

    assert "SIGNED KEY=fw-signing-2026-current" in output
    assert "revoked" not in output.lower()


def test_required_output_is_generated():
    result = run_publisher()

    assert result.returncode == 0

    output = result.stdout

    for bundle_id in EXPECTED_BUNDLES:
        assert (
            f"BUNDLE {bundle_id} SIGNED "
            "KEY=fw-signing-2026-current"
        ) in output

        assert (
            f"BUNDLE {bundle_id} PUBLISHED "
            f"RECEIPT="
        ) in output

        assert (
            f"TOKEN=token-{bundle_id} "
            "STATUS=PUBLISHED"
        ) in output


def test_fully_withdrawn_bundle_is_not_published():
    rows = read_publications()

    bundle_ids = {
        row[0]
        for row in rows
    }

    assert "BND-104" not in bundle_ids


def test_publisher_is_idempotent():
    first = run_publisher()

    assert first.returncode == 0, (
        f"First run failed:\n{first.stderr}"
    )

    first_rows = read_publications()

    second = run_publisher()

    assert second.returncode == 0, (
        f"Second run failed:\n{second.stderr}"
    )

    second_rows = read_publications()

    # No additional publications should have been created.
    assert len(second_rows) == len(first_rows)

    # Existing receipts should be reused.
    assert second_rows == first_rows


def test_second_run_produces_same_logical_output():
    first = run_publisher()

    assert first.returncode == 0

    second = run_publisher()

    assert second.returncode == 0

    first_output = normalize_output(first.stdout)
    second_output = normalize_output(second.stdout)

    assert first_output == second_output

